name: build and push

on:
  push:
    branches:
      - 'master'

jobs:
  docker_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Status
        uses: crazy-max/ghaction-docker-status@v1

  build:
    runs-on: ubuntu-latest
    needs: docker_status
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          # platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3
          tags: buluma/docker-buildx:latest
