---
name: Default CI

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: buluma/setup-buildx-action@0.1.3
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build . # will run buildx
