---
name: Max parallelism

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: buluma/setup-buildx-action@0.1.3
        with:
          config: .github/buildkitd.toml
